RA-03-create_buttons
mametich/BurgerShop pull request #2
Opened 2024-05-26 11:34 UTC by mametich

2024-05-28 21:05 UTC, ievetrovdev requested changes

2024-05-28 21:05 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +           android:layout_marginEnd="2dp"
тоже выносим в ресурсы

2024-05-28 21:05 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +       android:layout_marginBottom="8dp"
в ресурсы

2024-05-28 21:05 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="categories">категории</string>
Чтобы при глобальном поиске какой-то строки кода не попадали все значения в кучу, которые включают слово category – стоит для идентификатора этой строки сделать какое-то более общее название. Например, так title_categories. Это одна из причин. И в дальнейшем этот ресурс использовать и для заголовка экрана с категориями в шапке.

2024-05-28 21:05 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="blue_button">#525DC0</color>
Предлагаю такой формат названия ресурсов, например category_color. "color" в конце обязательно для отделения одного типа ресурса от другого.

2024-05-28 21:05 UTC, ievetrovdev commented on app/src/main/res/values/style.xml
> +        <item name="android:textSize">16sp</item>
размер шрифта тоже выносится в ресурсы

2024-05-28 21:05 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +          app:icon="@drawable/heart"
Верно, но изображение кажется можно было выгружать из фигмы вместе с фреймом. Если сам внутренний вектор грузить – он деформируется (становится уже)

2024-05-28 21:05 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
>      tools:context=".MainActivity">
В MainActivity есть свой фон и он отличается от чистого белого. В ресурсах его можно назвать main_background_color и переиспользовать на всех остальных экранах.

2024-06-12 12:50 UTC, ievetrovdev requested changes

2024-06-12 12:50 UTC, ievetrovdev commented on app/src/main/res/drawable/heart.png
иконки как правило выгружаются вектором (в свг). чтобы на любом масштабе и экране четко отображались.

2024-06-12 12:50 UTC, ievetrovdev commented on app/src/main/res/values/dimen.xml
> +    <dimen name="button_margin_start_2">2dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-06-12 12:50 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="favourites">избранное</string>
тут тоже стоит добавить префикс title_

2024-06-12 12:50 UTC, ievetrovdev commented on app/src/main/res/values/style.xml
> +        <item name="cornerRadius">8dp</item>
ресурсы

2024-06-12 14:42 UTC, ievetrov requested changes
<img width="288" alt="Снимок экрана 2024-06-12 в 17 41 55" src="https://github.com/mametich/BurgerShop/assets/34489023/54869f79-90b6-4a84-b299-f836d72ea527">

надо заменить на вектор

2024-06-13 20:15 UTC, ievetrovdev approved these changes
Только не забудь удалить пнг изображение сердца

2024-06-14 06:13 UTC, merged