RA-35-retrofit
mametich/BurgerShop pull request #33
Opened 2024-09-14 20:53 UTC by mametich

2024-09-15 13:08 UTC, ievetrovdev requested changes

2024-09-15 13:08 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/RecipesRepository.kt
> +private const val BASE_URL = "https://recipes.androidsprint.ru/api/"
В Котлине не принято выносить константы за пределы классов в глобальную зону видимости. Важно соблюдать ООП принцип  инкапсуляции. Константы, как правило, относятся к функционалу конкретного класса или объекта, поэтому логично хранить их в пределах этих объектов.
Давай вынесим их в companion object внутри класса.

2024-09-15 13:08 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/RecipesRepository.kt
> +    private val contentType = "application/json".toMediaType()
саму строку лучше тоже вынести в константы

2024-09-15 13:08 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/category/CategoriesListViewModel.kt
>      //TODO load from network
тудушки уже можно убрать)

2024-09-15 13:08 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/recipes/favorites/FavoritesListFragment.kt
> +            newFavoritesListState.listOfFavoriteRecipes ?: emptyList()
сейчас эта строчка ничего не делает, нету присвоения значения

2024-09-15 13:08 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/RecipesRepository.kt
> +        thread.join()
Сейчас твои потоки работают синхронно, ты их стартуешь и ждешь выполнения. По сути сами потоки сейчас не работают, без них была такая же логика.
Предлагаю все функции переписать по такому плану:
Функции репозитория пусть имеют параметр типа лямбды например callback: `(List<Category>) -> Unit` .  Сами они ничего не возвращают. В репозитории мы кладем это значение в лямбду, а во viewModel внутри лямбда-функции присваиваем это значение для state.
То есть в repository мы пишем callback(result), от thread.join() избавляемся.
Во viewModel в функцию передаем
recipesRepository.getCategories{
_categoryListUiState.value = CategoriesListUiState(
listOfCategory = it
)
}

2024-09-15 13:10 UTC, ievetrovdev commented
Также при выключенном интернете сейчас падает приложение, нужно правильно перехватывать ошибки

2024-09-17 06:43 UTC, ievetrovdev requested changes

2024-09-17 06:43 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/RecipesRepository.kt
> +    //Иван вообще не могу понять, почему этот код не работает приложение крашиться
Комментарии пиши или в самом ПР (как этот) или в ЛС на крайний случай. В файле не стоит устраивать чат, все это остается в истории проекта.

2024-09-17 06:43 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/RecipesRepository.kt
> +    private val retrofit = Retrofit.Builder()
Хорошо! но я бы оставил интерцептор, иначе без логов останемся. обычно для dev Build Variant его оставляют, а в прод сборку не включают.

2024-09-17 06:43 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/RecipesRepository.kt
> +    private val retrofit = Retrofit.Builder()
Особенно это актуально, когда есть проблемы в приложении, если нужно больше информации для выяснении причины багов.

2024-09-17 06:43 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/RecipesRepository.kt
> +//    fun getCategoryById(id: Int, callback: (Category?) -> Unit) {
Комментированный код в проде стараемся не оставлять

2024-09-17 06:43 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/category/CategoriesListViewModel.kt
> +                _categoryListUiState.value = CategoriesListUiState(
Привыкай копировать предыдущий стейт с изменением необходимых полей, а не создавать новый – хорошая практика. Причем копируем из публичной LiveData. Это избавит от текущих и будущих багов.

2024-09-17 06:43 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/api/RecipeApiService.kt
> +    fun getRecipes(ids: MutableSet<String>) : Call<List<Recipe>>
> Предлагаю более конкретно именовать методы и параметры. Для получения одного рецепта по айди – `getRecipeById(id: String?)`. Для списка рецептов по списку айди – `getRecipesByIds(set: Set<Int>)`.

2024-09-17 06:43 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/api/RecipeApiService.kt
> +    fun getRecipes(ids: MutableSet<String>) : Call<List<Recipe>>
Обрати внимание как отрабатывает запрос на получение списка рецептов по списку ID – getRecipesByIds. https://recipes.androidsprint.ru/api/docs. 

Попробуй отправить через запятую список чисел и в Request URL увидишь конструкцию ?ids=... Это будет говорить о том, что, чтобы получить необходимый список, нужно сначала отправить свой список айдишников с помощью Query запроса.

2024-09-17 06:43 UTC, ievetrovdev commented on app/build.gradle.kts
> +    implementation (libs.retrofit)
После слова implementation пробел не ставится

2024-09-18 19:23 UTC, ievetrovdev commented
Сейчас, если запустить приложение с выключенным интернетом - оно упадёт. Это связано с тем, что в MainActivity до сих пор работает тестовый код из прошлого ПР, где нету обработки ошибок. Его уже можно убрать. Скорее всего пойдут новые ошибки в других местах. 
Проверь с выключенным интернетом разные места приложения, будут креши. Большинство проблем решит замена прямого присвоения через =(setValue) на postValue. Основная его особенность в том, что postValue() не обновляет значение liveData сразу. Вместо этого оно помещает обновление в очередь на выполнение в главном потоке. Когда главный поток становится свободен, значение обновляется, и тогда наблюдатели будут уведомлены. Всё наше приложение щас работает в главном потоке, созданные нами Threads это уже другие потоки. Нельзя так просто менять значение переменной главного потока из сторонних без синхронизации.
Также в блоках catch в Repository рекомендую возвращать не пустой список, а null и обрабатывать эту ситуацию во ViewModel. Либо же в нужных местах проверять list на isEmpty. Может возникнуть ситуации, когда индекс будет выходить за пределы списка

2024-09-19 12:48 UTC, ievetrovdev requested changes

2024-09-19 12:48 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/recipes/listOfRecipes/RecipesListViewModel.kt
> +                            listOfRecipes = recipes,
Сейчас у тебя проблема, стирается шапка у рецептов. Это связано с тем, что ты создаешь новый стейт, а не копируешь предыдущий.  В какой-то момент стартый стейт стирается и заменяется на новый. 
До этого я рекомендовал тебе везде использовать copy, вместо присваения нового стейта. Всплыло одно из последствий неиспользования. 
В этом месте и других местах проекта, меняй стейт через такую конструкцию
_listOfRecipesUiState.postValue(_listOfRecipesUiState.value?.copy(...))

2024-09-19 12:48 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/recipes/listOfRecipes/RecipesListViewModel.kt
> +                    _listOfRecipesUiState.value = listOfRecipesUiState.value?.copy(
здесь до сих пор используется обычное присвоение, а не postValue

2024-09-19 12:48 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/recipes/listOfRecipes/RecipesListViewModel.kt
> +                    Toast.makeText(application.baseContext, "Ошибка получения данных", Toast.LENGTH_SHORT).show()
Приложение с выключенным интернетом падает до сих пор. Теперь это связано с вызовом  Toast.makeText не в главном потоке.  Всё что написано в этой лямбде, будет вызвано внутри Thread, при отработки callback(). А это уже внешний поток, который мы создали самостоятельно.
В Logcat эта проблема выводится. 
Предлагаю вынеcти тосты в UI слой на уровень фрагмента, проверять state на null и выводить toast

2024-09-19 19:54 UTC, mametich commented on app/src/main/java/com/example/burgershop/ui/recipes/listOfRecipes/RecipesListViewModel.kt
> +                    Toast.makeText(application.baseContext, "Ошибка получения данных", Toast.LENGTH_SHORT).show()
Сложность управления потоками, нужно смотреть чтоб каждый поток запускался отдельно и настраивать его, нужны калбэки, по мне нужно писать

2024-09-20 17:38 UTC, ievetrovdev commented
Api лежит ни в одном из слоёв. В доке есть схема, Api является Источником данных (Data Source).  К источникам данных также будет относится локальное кэширование. Всё это должно храниться в слое data
![image](https://github.com/user-attachments/assets/da9c9e6c-4f24-4027-9654-b627562abfe9)

2024-09-20 17:57 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/category/CategoriesListViewModel.kt
> +                    _categoryListUiState.value?.copy(
Осталось еще небольшая проблема с поведением. При повороте экрана у нас перерисовывается экран. Но если отключить интернет, перевернуть и получить пустой экран, включить интернет, повернуть экран, то при правильной работе категории снова должны появиться. Щас так не работает. 
Это связано с тем, что в else ты стейту присваиваешь null, а не его переменным внутри.
Из-за этого,  когда код выполняет _categoryListUiState.value?.copy, наступает момент с value == null и copy не выполняется.
Поправь это, не полностью зануляй стейт, а только его внутренности.
Скорее всего проблема повоторяется в других вью моделях, глянь их тоже

2024-09-20 17:57 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/recipes/listOfRecipes/RecipesListViewModel.kt
> +                    Toast.makeText(application.baseContext, "Ошибка получения данных", Toast.LENGTH_SHORT).show()
В целом ответ на вопрос дал верный. Основная сложность реализации в том, что необходимо асинхронным способом передать результаты из потока в возвращаемое значение метода репозитория.

2024-09-20 18:01 UTC, ievetrovdev commented
Молодец, проделал большую работу! В весь проект внедрил сетевое получение данных и корректно обрабатываются ошибки. Осталось пофиксить небольшую проблему со стейтами и можно идти дальше

2024-09-20 18:50 UTC, ievetrovdev requested changes

2024-09-20 18:50 UTC, ievetrovdev commented on app/src/main/java/com/example/burgershop/ui/category/CategoriesListFragment.kt
> +            if (newCategoryListUiState != null) {
Стейты ты переписал верно, но забыл в  ui  части корректно обрабатывать эти ситуации. Больше не отправляются тосты, поскольку условие всегда true.
Достаточно проверять список на null

2024-09-21 19:13 UTC, ievetrovdev approved these changes
Всё верно! 🎉🎉🎉🎉

2024-09-21 19:16 UTC, mametich commented
Ура, наконец-то!!!

2024-09-21 19:16 UTC, merged