RA-44-Di
mametich/BurgerShop pull request #40
Opened 2024-10-23 20:02 UTC by mametich

2024-10-23 21:09 UTC, Churickoid requested changes
По основному заданию всё верно, молодец!
Давай очистим папку assets, она была нужна только на раннем этапе без сетевых запросов.
Также нужно привести в порядок файл strings. У тебя перемешаны camel case и snake case. Давай к единому стилю приведем его, и добавим в начало префикс title всем, чтоб при глобальном поиске сразу было понятно, что это строковой ресурс. 
Заметил также, что в item_ingridients не хватает ограничений для элементов, они спокойно наезжают друг на друга. На моём устройстве на рецепте Борща это происходит.  Нужно прописать для названия app:layout_constraintEnd_toStartOf до меры, а мере прописать app:layout_constraintEnd_toEndOf до родителя

2024-10-23 21:09 UTC, aGroupoid commented on app/src/main/java/com/example/burgershop/RecipesRepository.kt
> +    private val ioDispatcher: CoroutineContext,
не используется нигде, и так не особо принято делать, указывать в названии какой именно dispatcher.  Dispatchers.IO это константа, имеет смысл пробрасывать только просто dispatcher, а уже другие сущности режают какой это будет - io или  main. Но в данном случае это лишнее

2024-10-23 21:09 UTC, aGroupoid commented on app/src/main/java/com/example/burgershop/di/AppContainer.kt
> +    val repository = RecipesRepository(
лучше сделать приватной

2024-10-24 18:27 UTC, danelyan requested changes
Есть необработанные комменты от Арсения. И еще не нужные зависимости (комменты от меня)

2024-10-24 18:27 UTC, danelyan commented on app/build.gradle.kts
> +    implementation(libs.androidx.ui.desktop)
А для чего это?

2024-10-24 18:27 UTC, danelyan commented on gradle/libs.versions.toml
> +androidx-ui-desktop = { group = "androidx.compose.ui", name = "ui-desktop", version.ref = "uiDesktop" }
нам тут не нужен compose

2024-10-26 20:15 UTC, Churickoid approved these changes
Всё верно, молодец!

2024-10-26 20:16 UTC, merged